name: db

on:
  workflow_run:
    workflows: [backend]
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.REGION }}
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Experimental status
        run: |
          docker version -f '{{.Server.Experimental}}' 

      - name: Plain job
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json 
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'