name: frontend

on:
  push:
    branches: [ master ]    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: | 
          cd frontend && cd infrastructure
          terraform init -input=false -backend-config="bucket=psi-docker-repo" -backend-config="key=fe/terraform.tfstate"

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Validate
        run: |
          cd frontend && cd infrastructure
          terraform validate 

      # Generates an execution plan for Terraform
      - name: Terraform Plan & Apply
        run: | 
          cd frontend && cd infrastructure
          terraform plan -var repository_name=${{ secrets.ECR_FE_REPOSITORY }} -out=tfplan
          terraform apply -input=false -auto-approve tfplan
